document.writeln("		<!--第五部分 咨询站-->");
document.writeln("				<div class=\'col-lg-12\' style=\'text-align: center; margin-top: 80px;\'>");
document.writeln("					<div style=\'background-color: #f7f7f7; height: 200px; width: 100%;padding-left: 150px;\'>");
document.writeln("						");
document.writeln("						<div style=\'border: 1px solid #f3f8fb;height: 200px;width: 1100px;\'>");
document.writeln("							<table style=\'margin-top:30px; width: 100%;height: 100px; font-size: 12px;\'>");
document.writeln("								<tbody>");
document.writeln("									<tr>");
document.writeln("										<td>咨询邮箱</td>");
document.writeln("										<td>手机站扫站</td>");
document.writeln("										<td>关注存不存</td>");
document.writeln("										<td><a href=\'#\'>我要寄存</a></td>");
document.writeln("										<td><a href=\'#\'>预定须知</a></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("										<td>");
document.writeln("											<h4>E-mail:cbcstorage@hotmail.com</h4></td>");
document.writeln("										<td>");
document.writeln("											<img src=\'../中级项目imges/页脚.png\'/></td>");
document.writeln("										<td>");
document.writeln("											<a href=\'javascript:btnClick3()\'><img src=\'../中级项目imges/页脚1.png\' /></a>");
document.writeln("											<a href=\'javascript:btnClick2()\'><img src=\'../中级项目imges/页脚2.png\' /></a>");
document.writeln("										</td>");
document.writeln("										<td><a href=\'#\'>关于存不存</a></td>");
document.writeln("										<td><a href=\'#\'>预定流程</a></td>");
document.writeln("									</tr>");
document.writeln("									<tr>");
document.writeln("										<td></td>");
document.writeln("										<td></td>");
document.writeln("										<td></td>");
document.writeln("										<td><a href=\'#\'>服务与帮助</a></td>");
document.writeln("										<td><a href=\'#\'>商务合作</a></td>");
document.writeln("									</tr>");
document.writeln("								</tbody>");
document.writeln("							</table>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("					");
document.writeln("					<!--第六部分 页脚-->");
document.writeln("					<div id=\'c2\' style=\'height: 200px;margin-top: 80px; font-size: 12px;font-family: 微软雅黑, Arial, Helvetica\'>");
document.writeln("						<div style=\'margin-top: 10px;\'>© 2019 www.cunbcX.com 存不存版权所有</div>");
document.writeln("						<div style=\'margin-top: 10px;\'>备案号： 苏ICP备19009XXX号 苏公网安备案 营业执照MA1WRXXXX 存不存保障计划</div>");
document.writeln("						<div style=\'margin-top: 10px;\'>");
document.writeln("							地址：");
document.writeln("							<a href=\'#\'>南京市江宁区秣陵街道科建路XXX号</a>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");